import { useState } from 'react';
import { AppFrame } from '../components/PageFrame';
import { formatCOP, products } from '../data';

export default function Cart() {
  const [quantity, setQuantity] = useState(2);
  const product = products[0];
  const subtotal = product.price * quantity;
  return <AppFrame active="Catálogo" footer><main className="page-container"><div className="container"><div className="content-heading"><div><span className="eyebrow">Tu compra</span><h1>Carrito</h1><p>Revisa tus productos antes de enviar una solicitud.</p></div><span className="cart-count">3 artículos</span></div><div className="cart-layout"><section className="surface"><div className="cart-item"><div className="cart-thumb" style={{ background: product.color }}>{product.emoji}</div><div className="cart-item-copy"><span className="category-pill">{product.category}</span><h3>{product.name}</h3><p>{product.farmer} · {product.location}</p><a className="text-link" href="/product/1">Ver producto</a></div><div className="cart-quantity"><label>Cantidad</label><input type="number" value={quantity} min="1" onChange={(event) => setQuantity(Number(event.target.value))} /></div><strong className="cart-item-total">{formatCOP(subtotal)}</strong><button className="remove-button">×</button></div><div className="cart-item"><div className="cart-thumb" style={{ background: products[2].color }}>{products[2].emoji}</div><div className="cart-item-copy"><span className="category-pill">{products[2].category}</span><h3>{products[2].name}</h3><p>{products[2].farmer} · {products[2].location}</p><a className="text-link" href="/product/3">Ver producto</a></div><div className="cart-quantity"><label>Cantidad</label><input type="number" defaultValue="12" min="1" /></div><strong className="cart-item-total">{formatCOP(products[2].price * 12)}</strong><button className="remove-button">×</button></div><a href="/catalog" className="btn-ghost">← Seguir explorando</a></section><aside className="surface order-summary"><h2>Resumen de solicitud</h2><div><span>Subtotal</span><strong>{formatCOP(subtotal + products[2].price * 12)}</strong></div><div><span>Transporte estimado</span><strong>Por confirmar</strong></div><div className="summary-total"><span>Total estimado</span><strong>{formatCOP(subtotal + products[2].price * 12)}</strong></div><button className="btn-primary" style={{ width: '100%' }} onClick={() => window.alert('Vista visual: solicitud preparada.')}>Continuar solicitud →</button><small>El precio final y la entrega se coordinan con cada productor.</small></aside></div></div></main></AppFrame>;
}
