import { FormEvent, useState } from 'react';
import { AppFrame } from '../components/PageFrame';

export default function Conversation() {
  const [message, setMessage] = useState('');
  const [sent, setSent] = useState<string[]>([]);
  const send = (event: FormEvent) => { event.preventDefault(); if (message.trim()) { setSent((items) => [...items, message.trim()]); setMessage(''); } };
  return <AppFrame active="Mensajes"><main className="page-container"><div className="container"><a href="/inbox" className="back-link">← Volver a mensajes</a><div className="message-layout conversation-page"><aside className="message-list"><div className="message-list-header"><h3>Conversaciones</h3></div><a className="message-card active" href="/conversation"><span className="avatar">ML</span><div className="message-copy"><strong>María Fernanda López</strong><small>AgroExport S.A.S.</small><p>Nos interesa el lote de café...</p></div></a></aside><section className="conversation"><header className="conversation-header"><span className="avatar">ML</span><div><h3>María Fernanda López</h3><p>AgroExport S.A.S. · <span style={{ color: '#39a64a' }}>en línea</span></p></div><a className="icon-action" href="/product/1" style={{ marginLeft: 'auto' }}>↗</a></header><div className="conversation-body"><div className="date-divider">Hoy, 15 de agosto</div><div className="bubble">Hola Carlos, vimos tu publicación de café especial de altura.<small>09:38</small></div><div className="bubble">Nos interesa el lote de 80 kg. ¿Podrías compartirnos disponibilidad y condiciones de transporte?<small>09:39</small></div><div className="bubble me">¡Hola María! Claro, tengo disponibilidad y transporte hasta Bogotá. Te comparto la información de la publicación.<small>09:41 · leído</small></div>{sent.map((item, index) => <div className="bubble me" key={`${item}-${index}`}>{item}<small>ahora</small></div>)}</div><form className="conversation-compose" onSubmit={send}><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Escribe un mensaje..." /><button className="btn-primary" type="submit">Enviar</button></form></section></div></div></main></AppFrame>;
}
