import { FormEvent, useState } from 'react';
import { AppFrame } from '../components/PageFrame';
import { getProduct } from '../data';

export default function EditarPublicacion() {
  const product = getProduct(Number(window.location.pathname.split('/').pop()) || 1);
  const [saved, setSaved] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); setSaved(true); };
  return <AppFrame active="Publicaciones" footer><main className="page-container"><div className="container narrow"><a href="/farmer-publications" className="back-link">← Mis publicaciones</a><div className="content-heading"><div><span className="eyebrow">Actualizar oferta</span><h1>Editar publicación</h1><p>Actualiza la información que ven los compradores.</p></div></div>{saved && <div className="page-notice success" style={{ marginBottom: 18 }}>Los cambios se guardaron en la vista de demostración.</div>}<form className="surface" onSubmit={submit}><div className="form-grid"><label className="form-field"><span>Nombre del producto</span><input defaultValue={product.name} /></label><label className="form-field"><span>Categoría</span><select defaultValue={product.category}><option>Frutas</option><option>Verduras</option><option>Granos</option><option>Café</option><option>Lácteos</option><option>Tubérculos</option></select></label><label className="form-field full"><span>Descripción</span><textarea rows={4} defaultValue={product.description} /></label><label className="form-field"><span>Precio por {product.unit}</span><input type="number" defaultValue={product.price} /></label><label className="form-field"><span>Cantidad disponible</span><input type="number" defaultValue={product.quantity} /></label><label className="form-field"><span>Unidad</span><select defaultValue={product.unit}><option>kg</option><option>litro</option><option>bulto</option><option>frasco</option></select></label><label className="form-field"><span>Ubicación</span><input defaultValue={product.location} /></label></div><div className="form-section"><label className="checkbox-line"><input type="checkbox" defaultChecked={product.transport} /> Mantener transporte disponible</label></div><div className="form-actions"><a href="/farmer-publications" className="btn-ghost">Cancelar</a><button className="btn-primary" type="submit">Guardar cambios →</button></div></form></div></main></AppFrame>;
}
