import { useState } from 'react';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import marketProduce from '../assets/market-produce.jpg';
import farmersMarket from '../assets/farmers-market.jpg';

const features = [
  ['📊', 'Gestión de cultivos', 'Registra y monitorea tus cultivos con información detallada de producción, fechas y cantidades.'],
  ['💬', 'Mensajería directa', 'Comunícate sin intermediarios con compradores y vendedores desde la plataforma.'],
  ['📦', 'Inventario inteligente', 'Controla tus cantidades disponibles y recibe alertas de stock en tiempo real.'],
  ['📅', 'Coordinación', 'Agenda encuentros y reuniones comerciales de forma fácil, rápida y organizada.'],
  ['⭐', 'Sistema de reputación', 'Construye confianza con calificaciones verificadas entre usuarios.'],
  ['📈', 'Reportes de venta', 'Genera reportes de producción y ventas para tomar mejores decisiones.']
];

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="home-page">
    <header className="home-header"><div className="home-header-inner"><a className="cx-brand" href="/"><span className="cx-brand-mark">🌾</span><span className="cx-brand-text">CoAgrix</span></a><div className={mobileOpen ? 'home-nav open' : 'home-nav'}><Navbar /></div><div className="home-actions"><a className="btn-outline" href="/login">Iniciar sesión</a><a className="btn-primary" href="/register">Registrarse</a></div><button className="home-menu" onClick={() => setMobileOpen((current) => !current)} aria-label="Abrir menú"><span /><span /><span /></button></div></header>
    <section className="hero" id="inicio"><div className="hero-orb one" /><div className="hero-orb two" /><div className="hero-grid" /><div className="container hero-inner"><div className="hero-copy"><span className="hero-badge">🚀 La evolución del campo colombiano</span><h1>Conectamos el <em>campo</em> con el <em>mercado</em></h1><p>CoAgrix facilita la comunicación entre agricultores y empresas compradoras, digitalizando la gestión de cultivos, inventarios y comercialización agrícola de forma simple y segura.</p><div className="hero-buttons"><a className="btn-accent btn-lg" href="/register">Comenzar gratis →</a><a className="hero-link" href="#funcionalidades">Ver funcionalidades ↓</a></div><div className="hero-trust"><div className="avatar-stack"><span>CM</span><span>ML</span><span>JG</span><span>+500</span></div><span><strong>+500 productores</strong><br />ya están creciendo con CoAgrix</span></div></div><div className="hero-visual"><div className="hero-photo hero-photo-main"><img src={marketProduce} alt="Productos agrícolas frescos" /></div><div className="hero-photo hero-photo-small"><img src={farmersMarket} alt="Mercado campesino" /></div><div className="floating-card floating-stock"><span>↗</span><div><strong>+24%</strong><small>ventas este mes</small></div></div><div className="floating-card floating-status"><span>✓</span><div><strong>Mercado activo</strong><small>386 publicaciones</small></div></div></div></div><div className="scroll-indicator">↓</div></section>
    <section className="impact"><div className="container impact-grid"><div><strong>+500</strong><span>Agricultores registrados</span></div><div><strong>+12k</strong><span>Toneladas comercializadas</span></div><div><strong>98%</strong><span>Satisfacción del cliente</span></div><div><strong>24/7</strong><span>Soporte técnico</span></div></div></section>
    <section className="features section-space" id="funcionalidades"><div className="container"><div className="section-heading"><span className="section-tag">Funcionalidades</span><h2>Todo lo que necesitas<br /><em>en un solo lugar</em></h2><p>Herramientas diseñadas para modernizar y potenciar el sector agroindustrial.</p></div><div className="feature-grid">{features.map(([icon, title, description]) => <article className="feature-card" key={title}><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{description}</p><a href="/register">Conocer más →</a></article>)}</div></div></section>
    <section className="showcase section-space"><div className="container showcase-grid"><div className="showcase-visual"><img src={marketProduce} alt="Variedad de productos frescos" /><div className="showcase-label"><span>🌿</span><div><strong>Productos frescos</strong><small>Directo del productor</small></div></div></div><div className="showcase-copy"><span className="section-tag">Un ecosistema conectado</span><h2>Del cultivo a la mesa,<br /><em>sin intermediarios</em></h2><p>Con CoAgrix, cada parte de la cadena agroalimentaria encuentra una forma más directa, justa y eficiente de trabajar.</p><div className="showcase-list"><div><span>01</span><p><strong>Publica y muestra</strong><br />Tu inventario siempre visible para compradores.</p></div><div><span>02</span><p><strong>Conecta y negocia</strong><br />Habla directamente con empresas y comerciantes.</p></div><div><span>03</span><p><strong>Crece con confianza</strong><br />Construye reputación y relaciones a largo plazo.</p></div></div></div></div></section>
    <section className="testimonials section-space" id="testimonios"><div className="container"><div className="section-heading centered"><span className="section-tag">Testimonios</span><h2>Lo que dice <em>el campo</em></h2></div><div className="testimonial-grid"><article className="testimonial-card"><span className="quote-mark">“</span><p>Desde que uso CoAgrix, he logrado vender mi cosecha de café un 30% más rápido y a mejor precio. La plataforma es muy fácil de usar.</p><div className="author"><span className="avatar">CM</span><div><strong>Carlos Mendoza</strong><small>Agricultor, Huila</small></div></div></article><article className="testimonial-card"><span className="quote-mark">“</span><p>La transparencia en el inventario y la comunicación directa nos ha ahorrado semanas de logística.</p><div className="author"><span className="avatar" style={{ background: '#d88b36' }}>ML</span><div><strong>María Fernanda López</strong><small>Gerente de compras, AgroExport</small></div></div></article></div></div></section>
    <section className="cta-section" id="contacto"><div className="container cta-inner"><span className="section-tag">Da el siguiente paso</span><h2>¿Listo para digitalizar<br /><em>tu negocio agrícola?</em></h2><p>Únete a cientos de agricultores y empresas que ya están creciendo con CoAgrix.</p><div><a className="btn-accent btn-lg" href="/register">Crear cuenta gratis →</a><a className="btn-outline light btn-lg" href="/login">Ya tengo cuenta</a></div></div></section>
    <Footer />
  </div>;
}
