import { useState } from 'react';
import { AppFrame } from '../components/PageFrame';
import { formatCOP, products } from '../data';

export default function MerchantCompare() {
  const [selected, setSelected] = useState('Aguacate Hass premium');
  const comparison = products.filter((product) => product.category === 'Frutas').slice(0, 3);
  return <AppFrame active="Favoritos" role="comerciante" footer><main className="page-container"><div className="container"><div className="content-heading"><div><span className="eyebrow">Decide mejor</span><h1>Comparador de productos</h1><p>Compara precios y condiciones antes de contactar a un proveedor.</p></div><a className="btn-outline" href="/favorites">← Mis favoritos</a></div><div className="surface compare-select"><label className="form-field"><span>Producto a comparar</span><select value={selected} onChange={(event) => setSelected(event.target.value)}>{products.slice(0, 5).map((product) => <option key={product.name}>{product.name}</option>)}</select></label><span className="compare-hint">Estás comparando {comparison.length} ofertas similares.</span></div><div className="surface compare-table"><div className="table-wrap"><table className="data-table"><thead><tr><th>Proveedor</th><th>Precio por kg</th><th>Disponibilidad</th><th>Transporte</th><th>Calificación</th><th /></tr></thead><tbody>{comparison.map((product, index) => <tr key={product.id}><td><div className="table-product"><span style={{ background: product.color }}>{product.emoji}</span><div><strong>{product.farmer}</strong><small>{product.location}</small></div></div></td><td className={index === 0 ? 'price-best' : ''}>{formatCOP(product.price)}{index === 0 && <small>Mejor precio</small>}</td><td>{product.quantity} kg</td><td><span className={`status-pill ${product.transport ? 'success' : 'neutral'}`}>{product.transport ? 'Disponible' : 'No incluido'}</span></td><td>★ 4.{9 - index}</td><td><button className="btn-primary btn-sm" onClick={() => window.alert(`Oferta de ${product.farmer} guardada.`)}>Guardar</button></td></tr>)}</tbody></table></div></div><div className="page-notice info" style={{ marginTop: 18 }}>Consejo: además del precio, revisa transporte, reputación y tiempos de respuesta para tomar una decisión informada.</div></div></main></AppFrame>;
}
