import { useState } from 'react';
import { AppFrame } from '../components/PageFrame';
import { Modal } from '../components/Utilities';
import { formatCOP, getProduct } from '../data';

export default function ProductDetail() {
  const id = Number(window.location.pathname.split('/').pop()) || 1;
  const product = getProduct(id);
  const [quantity, setQuantity] = useState(1);
  const [open, setOpen] = useState(false);
  return <AppFrame active="Catálogo" footer><main className="page-container"><div className="container"><a href="/catalog" className="back-link">← Volver al catálogo</a><div className="detail-layout"><section className="detail-visual" style={{ background: `linear-gradient(135deg, ${product.color}, #f4ead3)` }}><span>{product.emoji}</span><div className="detail-chip">{product.transport ? '🚚 Transporte disponible' : '📍 Entrega acordada'}</div></section><section className="surface detail-copy"><span className="category-pill">{product.category}</span><h1>{product.name}</h1><p className="detail-price">{formatCOP(product.price)} <small>/ {product.unit}</small></p><p className="muted">{product.description}</p><div className="detail-facts"><div><span>Disponibilidad</span><strong>{product.quantity} {product.unit}</strong></div><div><span>Ubicación</span><strong>{product.location}</strong></div><div><span>Calificación</span><strong>★ 4.9 / 5</strong></div></div><div className="seller-box"><span className="avatar large">{product.farmer.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><div><small>Publicado por</small><strong>{product.farmer}</strong><span>Productor verificado · 4 años en CoAgrix</span></div><a href="/conversation" className="icon-action">→</a></div><div className="detail-buy"><label className="form-field"><span>Cantidad ({product.unit})</span><input type="number" min="1" max={product.quantity} value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></label><div><small>Total estimado</small><strong>{formatCOP(product.price * quantity)}</strong></div></div><div className="form-actions"><button className="btn-outline" onClick={() => setOpen(true)}>♡ Guardar</button><button className="btn-primary" onClick={() => setOpen(true)}>Solicitar producto →</button></div></section></div><div className="detail-lower"><div className="surface"><h2>Información del producto</h2><p className="muted">Este producto cuenta con datos de origen compartidos por el agricultor. La compra y la coordinación se realizan de forma visual en esta demo, sin autenticación ni backend.</p><div className="info-list"><span>✓ Producto de origen campesino</span><span>✓ Inventario actualizado</span><span>✓ Comunicación directa</span></div></div><div className="surface"><h2>Productos relacionados</h2><div className="mini-products"><a href="/product/3">🍅 <span>Tomate chonto</span></a><a href="/product/5">🫐 <span>Mora de Castilla</span></a></div></div></div></div></main><Modal title="Solicitud enviada" open={open} onClose={() => setOpen(false)}><p className="muted">Tu solicitud de {quantity} {product.unit} de <strong>{product.name}</strong> quedó preparada para el agricultor. En la versión visual no se envía información al servidor.</p><button className="btn-primary" onClick={() => setOpen(false)}>Entendido</button></Modal></AppFrame>;
}
