import { DashboardFrame } from '../components/PageFrame';
import { DashboardStats } from '../components/Utilities';
import { dashboardByRole, orders, publications, Role } from '../data';

export default function RoleDashboard({ role }: { role: Role }) {
  const data = dashboardByRole[role];
  const active = 'Resumen';
  const roleTitle = role === 'agricultor' ? 'Tus publicaciones están generando interés' : role === 'empresa' ? 'Abastece tu operación con confianza' : 'Encuentra mejores oportunidades';
  return <DashboardFrame role={role} active={active}><div className="content-heading"><div><span className="eyebrow">{data.eyebrow}</span><h1>{data.title}</h1><p>{data.description}</p></div><span className="date-chip">Resumen · agosto 2026</span></div><DashboardStats stats={data.stats} /><div className="dashboard-columns"><section className="surface"><div className="surface-heading"><h2>{roleTitle}</h2><a className="text-link" href={role === 'agricultor' ? '/farmer-publications' : role === 'empresa' ? '/company-search' : '/merchant-compare'}>Explorar →</a></div><div className="insight-card"><span className="insight-icon">{role === 'agricultor' ? '🌱' : role === 'empresa' ? '🤝' : '⚖️'}</span><div><strong>{role === 'agricultor' ? '8 compradores revisaron tu café esta semana' : role === 'empresa' ? '14 proveedores tienen productos compatibles' : 'Puedes ahorrar hasta $680.000 con tus favoritos'}</strong><p>Revisa las recomendaciones y mantén activa tu red comercial.</p></div></div><div className="mini-chart"><div className="mini-bars">{[43, 65, 48, 80, 61, 92, 74].map((height, index) => <span style={{ height: `${height}%` }} key={index} />)}</div><div className="chart-labels"><span>Lun</span><span>Mar</span><span>Mié</span><span>Jue</span><span>Vie</span><span>Sáb</span><span>Dom</span></div></div></section><section className="surface"><div className="surface-heading"><h2>{role === 'agricultor' ? 'Pedidos recientes' : 'Actividad reciente'}</h2><a className="text-link" href="/orders">Ver todos →</a></div>{orders.slice(0, 3).map((order) => <div className="compact-order" key={order.id}><span className="order-icon">{order.product.slice(0, 1)}</span><div><strong>{order.product}</strong><small>{order.customer} · {order.date}</small></div><span className={`status-pill ${order.status === 'Entregado' ? 'success' : 'warning'}`}>{order.status}</span></div>)}</section></div><section className="surface"><div className="surface-heading"><h2>Accesos rápidos</h2></div><div className="quick-grid"><a className="quick-action" href={role === 'agricultor' ? '/create-publication' : '/catalog'}><span>{role === 'agricultor' ? '＋' : '🔎'}</span><div><strong>{role === 'agricultor' ? 'Crear publicación' : 'Explorar catálogo'}</strong><small>{role === 'agricultor' ? 'Muestra un producto nuevo' : 'Encuentra nuevas ofertas'}</small></div></a><a className="quick-action" href="/inbox"><span>💬</span><div><strong>Mensajes</strong><small>2 conversaciones sin leer</small></div></a><a className="quick-action" href={role === 'agricultor' ? '/farmer-profile' : role === 'empresa' ? '/company-profile' : '/favorites'}><span>👤</span><div><strong>{role === 'comerciante' ? 'Mis favoritos' : 'Mi perfil'}</strong><small>Gestiona tu información</small></div></a></div></section></DashboardFrame>;
}
